version: "3.7"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # - SERVICES=s3    # Only start the S3 service
      - SERVICES=iam, s3
      - DEBUG=1        # Enable debug mode
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=my-local-bucket
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_AUTH_TOKEN=ls-dedAjUVi-jIbI-LUxa-9205-FiHINiGa3309
    command: ["create-s3-bucket.sh"]
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./aws:/etc/localstack/init/ready.d